name: Publish





on:
  push:
    tags:
      - vt/*





jobs:

  Publishing:
    name: Publish
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/

      - run: npm install
        env:
          ADBLOCK: true
          DISABLE_OPENCOLLECTIVE: true
          HUSKY_SKIP_INSTALL: true

      - run: npm publish --tag=next --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - run: curl -X PUT -sLo /dev/null https://npm.taobao.org/sync/$(jq -r '.name' package.json)?sync_upstream=true &

