name: Publish docs only
on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: Which branch to deploy docs from
        required: true
        options:
          - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
      - run: npm run all:link
      - run: pnpm i -r
      - run: npm run all:check
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages
          destination_dir: docs
