name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          cache: true
          run_install: true
      - name: Setup WARP
        uses: fscarmen/warp-on-actions@v1.4
      - run: npm run all:check
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages
          destination_dir: docs
      - run: npm pkg delete devDependencies scripts pnpm --workspaces
      - run: npm publish --access public --provenance --workspaces
